#	$OpenBSD: Makefile.inc,v 1.2.6.3 2004/02/19 10:57:18 niklas Exp $

SRCS+=	__main.c imax.c imin.c lmax.c lmin.c max.c min.c ulmax.c ulmin.c \
	memchr.c memcmp.c memset.c bcmp.c random.c \
	strcmp.c strlcat.c strlcpy.c strlen.c strncmp.c \
	strncpy.c scanc.c skpc.c strncasecmp.c ffs.S
