#	$OpenBSD: Makefile,v 1.4.4.1 2001/10/31 03:07:59 nate Exp $

.if ${MACHINE} == "sparc64"
SUBDIR= bootblk libsa libkern libz ofwboot ofwboot.net
.endif

SUBDIR+= installboot


.include <bsd.subdir.mk>
