#	$OpenBSD: Makefile,v 1.6.12.1 2001/05/14 21:37:20 niklas Exp $
#	$NetBSD: Makefile,v 1.15 1997/06/01 03:39:03 mrg Exp $

.if ${MACHINE} == "sparc"
SUBDIR= libsa libkern libz boot bootxx binstall
.endif

SUBDIR+= installboot

.include <bsd.subdir.mk>
