#	$OpenBSD: Makefile,v 1.5.2.1 2001/04/18 16:00:01 niklas Exp $
#	$NetBSD: Makefile,v 1.5 1995/09/15 21:05:21 pk Exp $

# arch/arc arch/wgrisc
SUBDIR=	arch/alpha arch/amiga arch/hp300 arch/i386 \
	arch/mac68k arch/mvme68k arch/pmax arch/powerpc \
	arch/sparc arch/vax arch/sun3

.include <bsd.subdir.mk>
