#	$OpenBSD: Makefile,v 1.2.4.3 2004/02/19 10:48:41 niklas Exp $

MAN=	mkboot.8
MANSUBDIR=hppa

.if ${MACHINE} == "hppa"
PROG=	mkboot
CC=	${HOSTCC}
LDSTATIC=	-static
.else
NOPROG=
.endif

.include <bsd.prog.mk>
