#	$OpenBSD: Makefile,v 1.5.22.1 2006/09/30 04:06:51 brad Exp $

.PATH:		${.CURDIR}/..

PROG=	sftp-server
BINOWN=	root

BINMODE?=555

BINDIR=	/usr/libexec
MAN=	sftp-server.8

SRCS=	sftp-server.c sftp-common.c

.include <bsd.prog.mk>
