#	$OpenBSD: Makefile,v 1.4.8.1 2001/04/18 16:11:43 niklas Exp $
.if ${MACHINE} == "mvme88k"

SUBDIR=  bugcrt libbug libsa libz wrtvid bootsd bootxx bootst netboot
#sboot XXX future
.endif

SUBDIR+=installboot

.include <bsd.subdir.mk>
