#	$OpenBSD: Makefile,v 1.16.4.1 2001/04/18 16:05:45 niklas Exp $
#	$NetBSD: Makefile,v 1.23 1997/02/04 03:51:37 thorpej Exp $

.if ${MACHINE} == "hp300"
SUBDIR=	libsa libsaz libkern libz common mkboot uboot cdboot installboot
.endif

.include <bsd.subdir.mk>
