#	$OpenBSD: Makefile,v 1.10.8.1 2001/05/14 21:37:38 niklas Exp $	
#	$NetBSD: Makefile,v 1.21 1999/03/06 16:36:04 ragge Exp $
#

.if ${MACHINE} == "vax"
SUBDIR=	boot xxboot
.endif

.include <bsd.subdir.mk>
