#	$OpenBSD: Makefile,v 1.1.1.1.16.2 2001/10/31 03:08:00 nate Exp $
#	$NetBSD: Makefile,v 1.5 1995/10/13 21:44:08 gwr Exp $

.if ${MACHINE} == "sun3"
SUBDIR= libsa bootxx ufsboot netboot tapeboot
.endif

SUBDIR+= installboot

.include <bsd.subdir.mk>
