#	$OpenBSD: Makefile,v 1.1.4.1 2001/05/14 22:26:04 niklas Exp $
#	$NetBSD: Makefile,v 1.1 1998/06/12 23:22:54 cgd Exp $

INCSDIR= /usr/include/dev/pckbc

INCS=	pckbdreg.h pckbdvar.h psmreg.h

.include <bsd.kinc.mk>
