#	$OpenBSD: Makefile,v 1.8.2.1 2001/02/16 20:13:26 jason Exp $

.PATH:		${.CURDIR}/..

PROG=	scp
BINOWN=	root

BINMODE?=555

BINDIR=	/usr/bin
MAN=	scp.1

SRCS=	scp.c log-client.c

.include <bsd.prog.mk>
