#	$OpenBSD: Makefile,v 1.7.2.2 2001/03/12 15:44:19 jason Exp $

.PATH:		${.CURDIR}/..

PROG=	scp
BINOWN=	root

BINMODE?=555

BINDIR=	/usr/bin
MAN=	scp.1

SRCS=	scp.c log-client.c

.include <bsd.prog.mk>
