#	$OpenBSD: Makefile,v 1.8.2.4 2001/05/07 21:09:40 jason Exp $

.PATH:		${.CURDIR}/..

PROG=	scp
BINOWN=	root

BINMODE?=555

BINDIR=	/usr/bin
MAN=	scp.1

SRCS=	scp.c scp-common.c

.include <bsd.prog.mk>
