#	$OpenBSD: Makefile,v 1.4.14.2 2001/04/18 16:10:42 niklas Exp $

.if ${MACHINE} == "mvme68k"
SUBDIR= bugcrt libbug libsa libz sboot netboot bootxx bootsd bootst \
	prtvid wrtvid
.endif

SUBDIR+=installboot

.include <bsd.subdir.mk>
