#	$OpenBSD: Makefile,v 1.1.2.1 2001/10/31 03:01:21 nate Exp $

.if ${MACHINE} == "mvmeppc"
SUBDIR=  bugcrt libbug libsa libz bootsd bootxx bootst tftpboot
#sboot XXX future
.endif

#SUBDIR+=installboot

.include <bsd.subdir.mk>
