#	$OpenBSD: Makefile.inc,v 1.1.2.1 2003/03/27 23:52:17 niklas Exp $

MDEC_DIR?=/usr/mdec
CFLAGS+=	-fno-stack-protector

# Load addresses for first and second stage bootstraps 
STAGE1_RELOC=4000
STAGE2_RELOC=6000
STAGE3_RELOC=6000


