#	$OpenBSD: Makefile,v 1.6.12.1 2001/04/18 16:01:39 niklas Exp $
#	$NetBSD: Makefile,v 1.7 1997/04/10 23:03:38 cgd Exp $

.if ${MACHINE} == "alpha"
SUBDIR=	boot bootxx netboot libkern libsa libz
.endif

SUBDIR+= setnetbootinfo installboot

.include <bsd.subdir.mk>
